owner: AugendLimited
repo: cimb-sg-upptime

sites:
  - name: Django DEV Health
    url: https://app-dev.sg.augend.io/health/
    maxResponseTime: 10000
  - name: Keycloak DEV OIDC
    url: https://auth-dev.sg.augend.io/realms/master/.well-known/openid-configuration
    maxResponseTime: 10000

  - name: Django QA Health
    url: https://app-qa.sg.augend.io/health/
    maxResponseTime: 10000
  - name: Keycloak QA OIDC
    url: https://auth-qa.sg.augend.io/realms/master/.well-known/openid-configuration
    maxResponseTime: 10000

  - name: Django UAT Health
    url: https://app-uat.sg.augend.io/health/
    maxResponseTime: 10000
  - name: Keycloak UAT OIDC
    url: https://auth-uat.sg.augend.io/realms/master/.well-known/openid-configuration
    maxResponseTime: 10000

  - name: Django PROD Health
    url: https://app-prod.sg.augend.io/health/
    maxResponseTime: 10000
  - name: Keycloak PROD OIDC
    url: https://auth-prod.sg.augend.io/realms/master/.well-known/openid-configuration
    maxResponseTime: 10000

status-website:
  cname: status.sg.augend.io
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CIMB SG Status
  introTitle: "CIMB SG Environment Status"
  introMessage: Status page for CIMB SG Django and Keycloak environment checks.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
